<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\saviaup.backend.Domain\saviaup.backend.Domain.csproj" />
    <ProjectReference Include="..\saviaup.backend.Core\saviaup.backend.Core.csproj" />
    <ProjectReference Include="..\saviaup.backend.Infrastructure\saviaup.backend.Infrastructure.csproj" />
    <ProjectReference Include="..\saviaup.backend.Shared\saviaup.backend.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SaviaUp.Backend.Api</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>33e04e24-6a9f-439b-a279-bc278322aae8</UserSecretsId>
  </PropertyGroup>

</Project>
