// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaviaUp.Backend.Infrastructure.Persistence;

#nullable disable

namespace SaviaUp.Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SaviaUpDbContext))]
    [Migration("20260821172409_AddCashRegisters")]
    partial class AddCashRegisters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.CashRegister", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_cash_registers_tenant_id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_cash_registers_tenant_normalized_name");

                    b.ToTable("cash_registers", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.CashRegisterShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OpenedByUserId");

                    b.HasIndex("TenantId", "ClosedAt");

                    b.ToTable("cash_register_shifts", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInventoryTracked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TenantId", "IsActive", "Name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.DiningArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TenantId", "Order")
                        .IsUnique();

                    b.ToTable("dining_areas", null, t =>
                        {
                            t.HasCheckConstraint("CK_dining_areas_Order_Positive", "\"Order\" > 0");
                        });
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentStock")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MeasurementUnitId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MinimumStock")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MeasurementUnitId");

                    b.HasIndex("TenantId", "CategoryId");

                    b.HasIndex("TenantId", "MeasurementUnitId");

                    b.HasIndex("TenantId", "IsActive", "NormalizedName");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("StockAfter")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("StockBefore")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IngredientId", "CreatedAt");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("inventory_movements", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.MeasurementUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedCode")
                        .IsUnique();

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("TenantId", "IsActive", "Name");

                    b.ToTable("measurement_units", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("modules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "orders",
                            IsActive = true,
                            Name = "Orders"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "tables",
                            IsActive = true,
                            Name = "Tables"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "inventory",
                            IsActive = true,
                            Name = "Inventory"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "products",
                            IsActive = true,
                            Name = "Products"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Code = "kitchen",
                            IsActive = true,
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Code = "reports",
                            IsActive = true,
                            Name = "Reports"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Code = "billing",
                            IsActive = true,
                            Name = "Billing"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Code = "settings",
                            IsActive = true,
                            Name = "Settings"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Code = "categories",
                            IsActive = true,
                            Name = "Categories"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Code = "cash_registers",
                            IsActive = true,
                            Name = "Cash Registers"
                        });
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.OrganizationParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("organization_parameters", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIncludedInCashOpening")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ModuleId");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "orders.read",
                            Description = "orders.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "orders.create",
                            Description = "orders.create",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "orders.cancel",
                            Description = "orders.cancel",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Code = "tables.read",
                            Description = "tables.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Code = "tables.manage",
                            Description = "tables.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Code = "inventory.read",
                            Description = "inventory.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Code = "inventory.manage",
                            Description = "inventory.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            Code = "products.read",
                            Description = "products.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            Code = "products.manage",
                            Description = "products.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            Code = "kitchen.read",
                            Description = "kitchen.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            Code = "reports.read",
                            Description = "reports.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            Code = "billing.manage",
                            Description = "billing.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            Code = "settings.manage",
                            Description = "settings.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            Code = "categories.read",
                            Description = "categories.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            Code = "categories.manage",
                            Description = "categories.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000016"),
                            Code = "inventory.stock.read",
                            Description = "inventory.stock.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000017"),
                            Code = "inventory.ingredients.read",
                            Description = "inventory.ingredients.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000018"),
                            Code = "inventory.ingredients.manage",
                            Description = "inventory.ingredients.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000019"),
                            Code = "inventory.movements.read",
                            Description = "inventory.movements.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            Code = "inventory.movements.manage",
                            Description = "inventory.movements.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000021"),
                            Code = "inventory.complements.read",
                            Description = "inventory.complements.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000022"),
                            Code = "inventory.complements.manage",
                            Description = "inventory.complements.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000023"),
                            Code = "tables.operate",
                            Description = "tables.operate",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000024"),
                            Code = "settings.organization.read",
                            Description = "settings.organization.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000025"),
                            Code = "settings.organization.manage",
                            Description = "settings.organization.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000026"),
                            Code = "settings.business.read",
                            Description = "settings.business.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000027"),
                            Code = "settings.business.manage",
                            Description = "settings.business.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000028"),
                            Code = "settings.payment-methods.read",
                            Description = "settings.payment-methods.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000029"),
                            Code = "settings.payment-methods.manage",
                            Description = "settings.payment-methods.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000030"),
                            Code = "settings.users.read",
                            Description = "settings.users.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000031"),
                            Code = "settings.users.manage",
                            Description = "settings.users.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000032"),
                            Code = "settings.roles.read",
                            Description = "settings.roles.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000033"),
                            Code = "settings.roles.manage",
                            Description = "settings.roles.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000034"),
                            Code = "cash-registers.read",
                            Description = "cash-registers.read",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000035"),
                            Code = "cash-registers.operate",
                            Description = "cash-registers.operate",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000036"),
                            Code = "cash-registers.manage",
                            Description = "cash-registers.manage",
                            ModuleId = new Guid("10000000-0000-0000-0000-000000000010")
                        });
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInventoryTracked")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("PreparationTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("NORMAL");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TenantId", "CategoryId");

                    b.HasIndex("TenantId", "Type");

                    b.HasIndex("TenantId", "IsActive", "NormalizedName");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("CK_products_PreparationTime_NonNegative", "\"PreparationTimeMinutes\" IS NULL OR \"PreparationTimeMinutes\" >= 0");

                            t.HasCheckConstraint("CK_products_SalePrice_Positive", "\"SalePrice\" > 0");

                            t.HasCheckConstraint("CK_products_Type", "\"Type\" IN ('NORMAL', 'COMBO')");
                        });
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SessionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.RestaurantTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveOrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActiveOrderTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiningAreaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCashRegister")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelivery")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("OccupiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PositionX")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PositionY")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("SQUARE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiningAreaId");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("TenantId", "DiningAreaId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("restaurant_tables", null, t =>
                        {
                            t.HasCheckConstraint("CK_restaurant_tables_ActiveOrderTotal", "\"ActiveOrderTotal\" >= 0");

                            t.HasCheckConstraint("CK_restaurant_tables_Capacity", "\"Capacity\" BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_restaurant_tables_PositionX", "\"PositionX\" BETWEEN -100000 AND 100000");

                            t.HasCheckConstraint("CK_restaurant_tables_PositionY", "\"PositionY\" BETWEEN -100000 AND 100000");

                            t.HasCheckConstraint("CK_restaurant_tables_Shape", "\"Shape\" IN ('SQUARE', 'ROUND', 'RECTANGLEHORIZONTAL', 'RECTANGLEVERTICAL')");
                        });
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Document")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("LogoData")
                        .HasColumnType("bytea");

                    b.Property<string>("LogoFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("RequiresOpenCashRegister")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ResponsibleName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("State")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.TenantInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("NormalizedEmail");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId", "NormalizedEmail")
                        .IsUnique();

                    b.ToTable("tenant_invitations", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisabledUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisabledUntil");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique();

                    b.ToTable("tenant_memberships", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.TenantPermission", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("TenantId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("tenant_permissions", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("LastTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LastTenantId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.CashRegister", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.CashRegisterShift", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.User", "OpenedByUser")
                        .WithMany()
                        .HasForeignKey("OpenedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("CashRegisterShifts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OpenedByUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Category", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Categories")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.DiningArea", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("DiningAreas")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Ingredient", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.Category", "Category")
                        .WithMany("Ingredients")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaviaUp.Backend.Domain.Entities.MeasurementUnit", "MeasurementUnit")
                        .WithMany("Ingredients")
                        .HasForeignKey("MeasurementUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Ingredients")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("MeasurementUnit");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.InventoryMovement", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.User", "CreatedByUser")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaviaUp.Backend.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("Movements")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Ingredient");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.MeasurementUnit", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("MeasurementUnits")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.OrganizationParameter", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Parameters")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.PaymentMethod", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Permission", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.Module", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Product", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Products")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SaviaUp.Backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.RestaurantTable", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.DiningArea", "DiningArea")
                        .WithMany("Tables")
                        .HasForeignKey("DiningAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("RestaurantTables")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiningArea");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Role", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Roles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaviaUp.Backend.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.TenantInvitation", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaviaUp.Backend.Domain.Entities.Role", "Role")
                        .WithMany("Invitations")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Invitations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("Role");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.TenantMembership", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaviaUp.Backend.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.TenantPermission", b =>
                {
                    b.HasOne("SaviaUp.Backend.Domain.Entities.Permission", "Permission")
                        .WithMany("TenantPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaviaUp.Backend.Domain.Entities.Tenant", "Tenant")
                        .WithMany("EnabledPermissions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Category", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.DiningArea", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.MeasurementUnit", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Module", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("TenantPermissions");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Role", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("CashRegisterShifts");

                    b.Navigation("Categories");

                    b.Navigation("DiningAreas");

                    b.Navigation("EnabledPermissions");

                    b.Navigation("Ingredients");

                    b.Navigation("InventoryMovements");

                    b.Navigation("Invitations");

                    b.Navigation("MeasurementUnits");

                    b.Navigation("Memberships");

                    b.Navigation("Parameters");

                    b.Navigation("PaymentMethods");

                    b.Navigation("Products");

                    b.Navigation("RestaurantTables");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("SaviaUp.Backend.Domain.Entities.User", b =>
                {
                    b.Navigation("InventoryMovements");

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
