using Microsoft.Extensions.DependencyInjection;
using SaviaUp.Backend.Core.Authentication;
using SaviaUp.Backend.Core.Billing;
using SaviaUp.Backend.Core.CashRegisters;
using SaviaUp.Backend.Core.Categories;
using SaviaUp.Backend.Core.Inventory;
using SaviaUp.Backend.Core.Navigation;
using SaviaUp.Backend.Core.Orders;
using SaviaUp.Backend.Core.Products;
using SaviaUp.Backend.Core.Security;
using SaviaUp.Backend.Core.Settings;
using SaviaUp.Backend.Core.Statistics;
using SaviaUp.Backend.Core.Tenants;
using SaviaUp.Backend.Core.Tables;
using SaviaUp.Backend.Core.Users;
using SaviaUp.Backend.Domain.Ports;

namespace SaviaUp.Backend.Core;

public static class CoreModule
{
    public static IServiceCollection AddCore(this IServiceCollection services)
    {
        services.AddScoped<ILoginUseCase, LoginUseCase>();
        services.AddScoped<IRegisterUseCase, RegisterUseCase>();
        services.AddScoped<IRefreshTokenUseCase, RefreshTokenUseCase>();
        services.AddScoped<IForgotPasswordUseCase, ForgotPasswordUseCase>();
        services.AddScoped<IResetPasswordUseCase, ResetPasswordUseCase>();
        services.AddScoped<ILogoutUseCase, LogoutUseCase>();
        services.AddScoped<IGetUserTenantsUseCase, GetUserTenantsUseCase>();
        services.AddScoped<ICreateTenantUseCase, CreateTenantUseCase>();
        services.AddScoped<ISelectTenantUseCase, SelectTenantUseCase>();
        services.AddScoped<IGetCurrentUserUseCase, GetCurrentUserUseCase>();
        services.AddScoped<IGetUserInfoUseCase, GetUserInfoUseCase>();
        services.AddScoped<IGetAvailableModulesUseCase, GetAvailableModulesUseCase>();
        services.AddScoped<IListCategoriesUseCase, ListCategoriesUseCase>();
        services.AddScoped<ICreateCategoryUseCase, CreateCategoryUseCase>();
        services.AddScoped<IUpdateCategoryUseCase, UpdateCategoryUseCase>();
        services.AddScoped<ISetCategoryStatusUseCase, SetCategoryStatusUseCase>();
        services.AddScoped<IDeleteCategoryUseCase, DeleteCategoryUseCase>();
        services.AddScoped<IListInventoryUseCase, ListInventoryUseCase>();
        services.AddScoped<IListIngredientsUseCase, ListIngredientsUseCase>();
        services.AddScoped<ICreateIngredientUseCase, CreateIngredientUseCase>();
        services.AddScoped<IUpdateIngredientUseCase, UpdateIngredientUseCase>();
        services.AddScoped<ISetIngredientStatusUseCase, SetIngredientStatusUseCase>();
        services.AddScoped<IDeleteIngredientUseCase, DeleteIngredientUseCase>();
        services.AddScoped<IListInventoryMovementsUseCase, ListInventoryMovementsUseCase>();
        services.AddScoped<ICreateInventoryMovementUseCase, CreateInventoryMovementUseCase>();
        services.AddScoped<IListMeasurementUnitsUseCase, ListMeasurementUnitsUseCase>();
        services.AddScoped<ICreateMeasurementUnitUseCase, CreateMeasurementUnitUseCase>();
        services.AddScoped<IUpdateMeasurementUnitUseCase, UpdateMeasurementUnitUseCase>();
        services.AddScoped<ISetMeasurementUnitStatusUseCase, SetMeasurementUnitStatusUseCase>();
        services.AddScoped<IDeleteMeasurementUnitUseCase, DeleteMeasurementUnitUseCase>();
        services.AddScoped<IListProductsUseCase, ListProductsUseCase>();
        services.AddScoped<ICreateProductUseCase, CreateProductUseCase>();
        services.AddScoped<IUpdateProductUseCase, UpdateProductUseCase>();
        services.AddScoped<ISetProductStatusUseCase, SetProductStatusUseCase>();
        services.AddScoped<IDeleteProductUseCase, DeleteProductUseCase>();
        services.AddScoped<IListDiningAreasUseCase, ListDiningAreasUseCase>();
        services.AddScoped<ICreateDiningAreaUseCase, CreateDiningAreaUseCase>();
        services.AddScoped<IUpdateDiningAreaUseCase, UpdateDiningAreaUseCase>();
        services.AddScoped<IReorderDiningAreasUseCase, ReorderDiningAreasUseCase>();
        services.AddScoped<IDeleteDiningAreaUseCase, DeleteDiningAreaUseCase>();
        services.AddScoped<IListRestaurantTablesUseCase, ListRestaurantTablesUseCase>();
        services.AddScoped<ICreateRestaurantTableUseCase, CreateRestaurantTableUseCase>();
        services.AddScoped<IUpdateRestaurantTableUseCase, UpdateRestaurantTableUseCase>();
        services.AddScoped<IDeleteRestaurantTableUseCase, DeleteRestaurantTableUseCase>();
        services.AddScoped<IGetTableOperationUseCase, GetTableOperationUseCase>();
        services.AddScoped<ISetTableOperationUseCase, SetTableOperationUseCase>();
        services.AddScoped<IUpdateTableOrderUseCase, UpdateTableOrderUseCase>();
        services.AddScoped<IGetActiveTableOrderUseCase, GetActiveTableOrderUseCase>();
        services.AddScoped<IGetOrdersPageUseCase, GetOrdersPageUseCase>();
        services.AddScoped<IGetOrderItemsPageUseCase, GetOrderItemsPageUseCase>();
        services.AddScoped<IAddTableOrderItemsUseCase, AddTableOrderItemsUseCase>();
        services.AddScoped<IMoveTableOrderUseCase, MoveTableOrderUseCase>();
        services.AddScoped<ICancelOrderItemUseCase, CancelOrderItemUseCase>();
        services.AddScoped<IPayAndCloseTableOrderUseCase, PayAndCloseTableOrderUseCase>();
        services.AddScoped<IGenerateSummaryReceiptUseCase, GenerateSummaryReceiptUseCase>();
        services.AddScoped<IGetOrderReceiptsUseCase, GetOrderReceiptsUseCase>();
        services.AddScoped<IListCashRegistersUseCase, ListCashRegistersUseCase>();
        services.AddScoped<ICreateCashRegisterUseCase, CreateCashRegisterUseCase>();
        services.AddScoped<IUpdateCashRegisterUseCase, UpdateCashRegisterUseCase>();
        services.AddScoped<ISetCashRegisterStatusUseCase, SetCashRegisterStatusUseCase>();
        services.AddScoped<IDeleteCashRegisterUseCase, DeleteCashRegisterUseCase>();
        services.AddScoped<IOpenCashRegisterShiftUseCase, OpenCashRegisterShiftUseCase>();
        services.AddScoped<ICloseCashRegisterShiftUseCase, CloseCashRegisterShiftUseCase>();
        services.AddScoped<IGetCashRegisterShiftSummaryUseCase, GetCashRegisterShiftSummaryUseCase>();
        services.AddScoped<IListCashRegisterShiftsUseCase, ListCashRegisterShiftsUseCase>();
        services.AddScoped<IOrganizationSettingsUseCase, OrganizationSettingsUseCase>();
        services.AddScoped<IBusinessSettingsUseCase, BusinessSettingsUseCase>();
        services.AddScoped<IPaymentMethodsSettingsUseCase, PaymentMethodsSettingsUseCase>();
        services.AddScoped<IAccessSettingsUseCase, AccessSettingsUseCase>();
        services.AddScoped<IGetStatisticsUseCase, GetStatisticsUseCase>();
        services.AddScoped<IGetBillingReceiptsUseCase, GetBillingReceiptsUseCase>();
        services.AddScoped<IGetBillingOrdersUseCase, GetBillingOrdersUseCase>();
        services.AddScoped<IGetBillingReceiptByIdUseCase, GetBillingReceiptByIdUseCase>();
        services.AddScoped<IPermissionService, PermissionService>();
        services.AddScoped<SessionIssuer>();
        services.AddSingleton<PasswordPolicy>();
        return services;
    }
}
